# Cloudtype 배포 설정 파일

# 1. 백엔드(Node.js) 서비스 설정
- name: chat-backend # 서비스 이름 (원하는 대로 지정 가능)
  app: node@18 # 사용할 앱 타입과 버전 (Node.js 18 버전 사용)
  options:
    port: 3001 # 백엔드 서버가 사용하는 포트 번호
    # 빌드 및 실행 관련 설정
    build: npm install
    start: npm start
    # 소스 코드가 있는 하위 폴더 지정
    subpath: chat-backend
  # 환경 변수 설정 (보안이 중요한 정보)
  env:
    - name: MONGO_URI
      value: mongodb+srv://admin:Hw120212@chatcluster.kn44nxa.mongodb.net/?retryWrites=true&w=majority&appName=chatCluster # 여기에 실제 MongoDB Atlas 연결 주소를 입력하세요.
    - name: JWT_SECRET
      value: "some-super-secret-key-that-is-long-and-random-!@#$" # 여기에 원하는 JWT 비밀 키를 입력하세요.

# 2. 프론트엔드(React) 서비스 설정
- name: chat-frontend # 서비스 이름
  app: web # 정적 웹사이트를 위한 앱 타입
  options:
    # 빌드 및 실행 관련 설정
    build: npm install && npm run build # 의존성 설치 후 빌드 실행
    docbase: chat-frontend/dist # 빌드 결과물(정적 파일)이 있는 폴더
    # SPA(Single Page Application) 설정
    spa: true
    # API 요청을 백엔드로 전달하기 위한 프록시(Proxy) 설정
    proxy:
      - path: /api
        forward: http://chat-backend:3001 # /api로 시작하는 모든 요청을 chat-backend 서비스의 3001 포트로 전달
      - path: /socket.io
        forward: http://chat-backend:3001 # 소켓 연결 요청도 백엔드로 전달
